# The base address of the user space.
user_space_base = 0x1000
# The size of the user space.
user_space_size = 0x7fff_ffff_f000

# The base address of the user heap.
user_heap_base = 0x3fc0_0000
# The size of the user heap.
user_heap_size = 0x40_0000

# The highest address of the user stack.
user_stack_top = 0x7fff_0000_0000
# The size of the user stack.
user_stack_size = 0x1_0000

# The size of the kernel stack.
kernel_stack_size = 0x40000