name: CI

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
    - name: Setup ArceOS
      run: ./scripts/get_deps.sh
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        rust-toolchain: [nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, llvm-tools
        targets: x86_64-unknown-none
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - name: Build for ${{ matrix.arch }}
      run: make ARCH=${{ matrix.arch }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly]
        arch: [x86_64]
    env:
      qemu-version: 8.2.0
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, llvm-tools
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - run: ./scripts/get_deps.sh
    - uses: ./.arceos/.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - uses: ./.arceos/.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - name: Run tests
      run: make test ARCH=${{ matrix.arch }}